name: Nest.js ci/cd pipeline

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: docker build -t dev-telegram-aurora .

  dev-deploy:
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - run: docker stop $(docker ps -q --filter ancestor=dev-aurora-telegram )
      - run: docker run -d -p3000:3000 --restart=always dev-aurora-telegram
        if: always()

